version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    volumes:
      - .:/react-redux-todoapp:cached
      - bundle:/usr/local/bundle
    ports:
      - "${EXTERNAL_RAILS_PORT:-5056}:5056"
    depends_on:
      - mongo
      - kvs
    tty: true
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    extra_hosts:
      - react-redux-todoapp.local:172.16.238.10

  mongo:
    build:
      context: .
      dockerfile: ./containers/mongo/Dockerfile
    volumes:
      - data_mongo:/data/db
    ports:
      - "${EXTERNAL_MONGO_PORT:-27020}:27020"

  kvs:
    build:
      context: .
      dockerfile: ./containers/kvs/Dockerfile
    ports:
      - "${EXTERNAL_REDIS_PORT:-6375}:6375"

volumes:
  data_mongo:
  bundle:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
